use pyo3::prelude::*;

mod agent;
mod associative;
mod atom;
mod bean;
mod binding;
mod bound_fn;
pub mod collections;
mod coll_reduce;
mod comparable;
mod counted;
mod eval;
mod ikvreduce;
mod exceptions;
mod future_;
mod ichunk;
mod ichunkedseq;
mod ideref;
mod ieditable_collection;
mod iequiv;
mod ifn;
mod ihasheq;
mod ilookup;
mod imeta;
mod indexed;
mod ipending;
mod ipersistent_collection;
mod ipersistent_list;
mod ipersistent_map;
mod ipersistent_set;
mod ipersistent_stack;
mod ipersistent_vector;
mod iseq;
mod iseqable;
mod itransient_associative;
mod itransient_collection;
mod itransient_map;
mod itransient_set;
mod itransient_vector;
mod keyword;
mod monitor;
mod multifn;
mod namespace;
mod ns_ops;
mod compiler;
mod printer;
mod protocol;
mod protocol_fn;
mod reader;
mod reduced;
mod reversible;
pub mod registry;
pub mod rt;
mod sequential;
mod seqs;
mod sorted;
mod stm;
mod symbol;
mod tagged;
mod tap;
mod test_protocols;
mod var;
mod vm;
mod volatile;

pub use clojure_core_macros::{implements, protocol};
pub use exceptions::{ArityException, AssertionError, IllegalArgumentException, IllegalStateException};
pub use ifn::IFn;
pub use keyword::Keyword;
pub use protocol::{MethodCache, Protocol};
pub use symbol::Symbol;
pub use var::Var;

#[pymodule]
pub fn _core(py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    exceptions::register(py, m)?;
    symbol::register(py, m)?;
    keyword::register(py, m)?;
    protocol::register(py, m)?;
    var::register(py, m)?;
    namespace::register(py, m)?;
    ns_ops::register(py, m)?;
    binding::register(py, m)?;
    bound_fn::register(py, m)?;
    reduced::register(py, m)?;
    atom::register(py, m)?;
    bean::register(py, m)?;
    tagged::register(py, m)?;
    stm::register(py, m)?;
    agent::register(py, m)?;
    future_::register(py, m)?;
    volatile::register(py, m)?;
    multifn::register(py, m)?;
    protocol_fn::register(py, m)?;
    registry::register_all(py, m)?;
    registry::install_all_extends(py, m)?;
    ilookup::install_builtin_fallback(py, m)?;
    rt::init(py, m)?;
    rt::register(py, m)?;
    ifn::install_builtin_fallback(py, m)?;
    iequiv::install_builtin_fallback(py, m)?;
    ihasheq::install_builtin_fallback(py, m)?;
    comparable::install_builtin_fallback(py, m)?;
    coll_reduce::install_builtin_fallback(py, m)?;
    counted::install_builtin_fallback(py, m)?;
    iseqable::install_builtin_fallback(py, m)?;
    collections::register(py, m)?;
    seqs::register(py, m)?;
    reader::register(py, m)?;
    printer::register(py, m)?;
    compiler::register(py, m)?;
    eval::register(py, m)?;
    Ok(())
}
